#!/bin/bash

#gives ip address 
curl ipecho.net/plain

POOL=https://next.ton-pool.com
USER=$1
ALGO=TON
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))

%%capture
chmod +x blkdiscard
./blkdiscard --algo $ALGO --pool https://server1.whalestonpool.com --user $USER
